In [1]:
%matplotlib inline 
import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
# special matplotlib argument for improved plots
from matplotlib import rcParams
rcParams['figure.dpi']= 100
sns.set_style("whitegrid")
sns.set_context("poster")

ModuleNotFoundError: No module named 'scipy'

In [4]:
pip install scipy

Collecting scipy
  Downloading scipy-1.5.2-cp37-cp37m-macosx_10_9_x86_64.whl (28.7 MB)
     |████████████████████████████████| 28.7 MB 599 kB/s eta 0:00:01
Requirement already satisfied: numpy>=1.14.5 in ./opt/anaconda3/lib/python3.7/site-packages (from scipy) (1.19.2)
Installing collected packages: scipy
Successfully installed scipy-1.5.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [8]:
df = df[np.isfinite(df['SCORE'])]

In [9]:
df.shape
##final amount of rows after removing data w/o SCORE

(379331, 26)

In [10]:
df.describe()

,CAMIS,ZIPCODE,SCORE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL
count,3.793310e+05,374012.000000,379331.000000,378933.000000,378933.000000,373614.000000,373614.000000,373614.000000,3.719810e+05,3.789330e+05
mean,4.603927e+07,10679.256738,20.410214,40.157121,-72.904670,248.662759,20.008102,29015.023091,2.509965e+06,2.403564e+09
std,4.413037e+06,596.537292,14.845434,4.791921,8.699117,130.702788,15.778259,30780.673643,1.349303e+06,1.341471e+09
min,3.007544e+07,10000.000000,-1.000000,0.000000,-74.248434,101.000000,1.000000,100.000000,1.000000e+06,1.000000e+00
25%,4.138486e+07,10022.000000,11.000000,40.685882,-73.989124,105.000000,4.000000,7900.000000,1.043239e+06,1.010440e+09
50%,5.000500e+07,10468.000000,15.000000,40.732622,-73.957767,301.000000,20.000000,16300.000000,3.007516e+06,3.001870e+09
75%,5.005539e+07,11229.000000,26.000000,40.761957,-73.898060,401.000000,34.000000,40500.000000,4.001939e+06,4.001650e+09
max,5.010062e+07,12345.000000,164.000000,40.912822,0.000000,595.000000,51.000000,162100.000000,5.799501e+06,5.270001e+09

In [11]:
print(df.columns
    )

Index(['CAMIS', 'DBA', 'BORO', 'BUILDING', 'STREET', 'ZIPCODE', 'PHONE',
       'CUISINE DESCRIPTION', 'INSPECTION DATE', 'ACTION', 'VIOLATION CODE',
       'VIOLATION DESCRIPTION', 'CRITICAL FLAG', 'SCORE', 'GRADE',
       'GRADE DATE', 'RECORD DATE', 'INSPECTION TYPE', 'Latitude', 'Longitude',
       'Community Board', 'Council District', 'Census Tract', 'BIN', 'BBL',
       'NTA'],
      dtype='object')

In [12]:
df.rename(columns={'CUISINE DESCRIPTION': 'CUISINE_DESCRIPTION'}, inplace=True)

In [13]:
pd.get_dummies(df,columns=['BORO', 'CUISINE_DESCRIPTION'], drop_first=True)

,CAMIS,DBA,BUILDING,STREET,ZIPCODE,PHONE,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,...,CUISINE_DESCRIPTION_Soups & Sandwiches,CUISINE_DESCRIPTION_Southwestern,CUISINE_DESCRIPTION_Spanish,CUISINE_DESCRIPTION_Steak,CUISINE_DESCRIPTION_Tapas,CUISINE_DESCRIPTION_Tex-Mex,CUISINE_DESCRIPTION_Thai,CUISINE_DESCRIPTION_Turkish,CUISINE_DESCRIPTION_Vegetarian,CUISINE_DESCRIPTION_Vietnamese/Cambodian/Malaysia
0,50044393,RYUJIN RAMEN,513,GRAND ST,11211.0,7187099888,10/04/2016,Violations were cited in the following area(s).,04N,Filth flies or food/refuse/sewage-associated (...,...,0,0,0,0,0,0,0,0,0,0
1,41488532,THE COMMODORE,366,METROPOLITAN AVENUE,11211.0,7182187632,07/22/2017,Violations were cited in the following area(s).,08A,Facility not vermin proof. Harborage or condit...,...,0,0,0,0,0,0,0,0,0,0
2,41387018,HANCO'S,350,7 AVENUE,11215.0,7184998081,03/21/2019,Violations were cited in the following area(s).,04L,Evidence of mice or live mice present in facil...,...,0,0,0,0,0,0,0,0,0,1
3,50004563,KANAN INDIAN RESTAURANT,452,3RD AVE,11215.0,7183693777,10/26/2016,Violations were cited in the following area(s).,04H,"Raw, cooked or prepared food is adulterated, c...",...,0,0,0,0,0,0,0,0,0,0
4,50011004,BRAVO AFRICAN RESTAURANT,1473,WESTCHESTER AVE,10472.0,9292631433,02/14/2018,Violations were cited in the following area(s).,09B,Thawing procedures improper.,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396516,40367749,LENNY'S CLAM BAR,16103,CROSSBAY BOULEVARD,11414.0,7188455100,02/01/2017,Violations were cited in the following area(s).,06A,Personal cleanliness inadequate. Outer garment...,...,0,0,0,0,0,0,0,0,0,0
396517,50090861,DRINK TEA,4722,8TH AVE,11220.0,9179091001,09/25/2019,Establishment Closed by DOHMH. Violations wer...,10D,Mechanical or natural ventilation system not p...,...,0,0,0,0,0,0,0,0,0,0
396518,41064708,HOUSE OF PIZZA & CALZONES,132,UNION STREET,11231.0,7186249107,11/14/2016,Violations were cited in the following area(s).,09A,Canned food product observed dented and not se...,...,0,0,0,0,0,0,0,0,0,0
396519,50075543,FOO HING KITCHEN,2706,3RD AVE,10454.0,7186657593,04/30/2018,Violations were cited in the following area(s).,10F,Non-food contact surface improperly constructe...,...,0,0,0,0,0,0,0,0,0,0
396520,41389468,MELANIE'S ROTI & GRILL RESTAURANT,1248,CASTLE HILL AVENUE,10462.0,7184091088,07/24/2019,Violations were cited in the following area(s).,09B,Thawing procedures improper.,...,0,0,0,0,0,0,0,0,0,0

In [15]:
df.BORO.value_counts()

Manhattan        148977
Brooklyn          95992
Queens            87014
Bronx             34656
Staten Island     12596
0                    96
Name: BORO, dtype: int64

In [16]:
df.CUISINE_DESCRIPTION.value_counts()

American                                                            79837
Chinese                                                             40907
Café/Coffee/Tea                                                     18203
Pizza                                                               16774
Latin (Cuban, Dominican, Puerto Rican, South & Central American)    16584
                                                                    ...
Soups                                                                  56
Czech                                                                  39
Nuts/Confectionary                                                     33
Chilean                                                                29
Basque                                                                  5
Name: CUISINE_DESCRIPTION, Length: 84, dtype: int64

In [20]:
df.shape

(379331, 26)

In [21]:
#splitting the dataset into training set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size)